<img style="float: left; margin: 30px 15px 15px 15px;" src="https://pngimage.net/wp-content/uploads/2018/06/logo-iteso-png-5.png" width="300" height="500" /> 
    
    
### <font color='navy'> Simulación de procesos financieros. 

**Nombre:** Fernando Flores.

**Fecha:** 11 de febrero del 2020.

**Expediente** : 714575.
**Profesor:** Oscar David Jaramillo Zuluaga.

# Tarea 2 - b): Clase 3


## Tarea 2
> Usando notebook de jupyter para generar programas de python.

### Ejercicio 1: 
- Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.
> 	- Expected Output:\\
> 	- Original List: [12.23, 13.32, 100, 36.32]\\
> 	- One-dimensional numpy array: [ 12.23 13.32 100. 36.32] 

In [5]:
# Código de solución 
import numpy as np
lista = [12.23, 13.32, 100, 36.32]
array = np.array(lista)
array

array([ 12.23,  13.32, 100.  ,  36.32])

### Ejercicio 2: 
- Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [6]:
# Código de solución
x = np.zeros(10)
x[6]=11
x

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

### Ejercicio 3: 
- Write a Python program to create a array with values ranging from 12 to 38.

In [7]:
# Código de solución
z = np.arange(12,39)
z

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

### Ejercicio 4: 
- Write a Python program to reverse an array (first element becomes last).

In [8]:
# Código de solución
c = np.arange(10,20)
ct = c[::-1]
c, ct

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10]))

### Ejercicio 5: 
> - Write a Python program to create a 2d array with 1 on the border and 0 inside.
>     
>     Expected Output:
> 	- Original array:
> 	$$
     \begin{pmatrix} 
     1. &1.& 1.& 1.& 1.\\
     1. &1.& 1.& 1.& 1.\\
     1. &1.& 1.& 1.& 1.\\
     1. &1.& 1.& 1.& 1.\\
     1. &1.& 1.& 1.& 1.
     \end{pmatrix}
    $$
> 	1 on the border and 0 inside in the array
     $$
     \begin{pmatrix} 
     1. &1.& 1.& 1.& 1.\\
     1. &0& 0& 0& 1.\\
     1. &0& 0& 0& 1.\\
     1. &0& 0& 0& 1.\\
     1. &1.& 1.& 1.& 1.
     \end{pmatrix}
    $$
> 
> - Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern
> 
> 	- Checkerboard pattern:
>     $$
     \begin{pmatrix} 
        0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
        1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
        0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
        1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
        0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 \\
        1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
        0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
        1 & 0 & 1 & 0 & 1 & 0 & 1 & 0
     \end{pmatrix}
     $$

In [9]:
# Código de solución
n = 10
d = np.ones((n,n), dtype=int)
d[1:-1,1:-1] = 0
d

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### Ejercicio 6: 
- Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [10]:
# Código de solución
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### Ejercicio 7: 
- Write a Python program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.
>     - Sample Array [0, 12, 45.21 ,34, 99.91]  
>     - Expected Output:
>     - Values in Fahrenheit degrees: [0.0 12.0 45.21 34.0 99.91]
>     - Values in Centigrade degrees: [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778].

In [25]:
# Código de solución
Farenheit = [0.0, 12.0, 45.21, 34.0, 99.91]
Centigrades = (np.array(Farenheit) - 32)*5/9
print('Values in Fahrenheit degrees: ', Farenheit)
print('Values in Centigrade degrees: ',Centigrades)

Values in Fahrenheit degrees:  [0.0, 12.0, 45.21, 34.0, 99.91]
Values in Centigrade degrees:  [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]
